window.Modernizr=function(y,g,m){function z(a,b){for(var c in a)if(j[a[c]]!==m&&(!b||b(a[c],A)))return true}function q(a,b){var c=a.charAt(0).toUpperCase()+a.substr(1);c=(a+" "+K.join(c+" ")+c).split(" ");return!!z(c,b)}var e={},n=g.documentElement,L=g.head||g.getElementsByTagName("head")[0],A=g.createElement("modernizr"),j=A.style;g.createElement("input");var r=" -webkit- -moz- -o- -ms- -khtml- ".split(" "),K="Webkit Moz O ms Khtml".split(" "),d={},D=[],t,E=function(a){var b=g.createElement("style"),
c=g.createElement("div");b.textContent=a+"{#modernizr{height:3px}}";L.appendChild(b);c.id="modernizr";n.appendChild(c);a=c.offsetHeight===3;b.parentNode.removeChild(b);c.parentNode.removeChild(c);return!!a};(function(){var a={select:"input",change:"input",submit:"form",reset:"form",error:"img",load:"img",abort:"img"};return function(b,c){c=c||g.createElement(a[b]||"div");b="on"+b;var o=b in c;if(!o){c.setAttribute||(c=g.createElement("div"));if(c.setAttribute&&c.removeAttribute){c.setAttribute(b,
"");o=typeof c[b]==="function";typeof c[b]===m||(c[b]=m);c.removeAttribute(b)}}return o}})();var B={}.hasOwnProperty,F;F=typeof B!==m&&typeof B.call!==m?function(a,b){return B.call(a,b)}:function(a,b){return b in a&&typeof a.constructor.prototype[b]===m};d.touch=function(){return"ontouchstart"in y||E("@media ("+r.join("touch-enabled),(")+"modernizr)")};d.rgba=function(){j.cssText="background-color:rgba(150,255,150,.5)";return(""+j.backgroundColor).indexOf("rgba")!==-1};d.borderradius=function(){return q("borderRadius",
"",function(a){return(""+a).indexOf("orderRadius")!==-1})};d.boxshadow=function(){return q("boxShadow")};d.textshadow=function(){return g.createElement("div").style.textShadow===""};d.opacity=function(){var a=r.join("opacity:.55;")+"";j.cssText=a;return/^0.55$/.test(j.opacity)};d.cssanimations=function(){return q("animationName")};d.cssgradients=function(){var a=("background-image:"+r.join("gradient(linear,left top,right bottom,from(#9f9),to(white));background-image:")+r.join("linear-gradient(left top,#9f9, white);background-image:")).slice(0,
-17);j.cssText=a;return(""+j.backgroundImage).indexOf("gradient")!==-1};d.cssreflections=function(){return q("boxReflect")};d.csstransforms=function(){return!!z(["transformProperty","WebkitTransform","MozTransform","OTransform","msTransform"])};d.csstransforms3d=function(){var a=!!z(["perspectiveProperty","WebkitPerspective","MozPerspective","OPerspective","msPerspective"]);if(a&&"webkitPerspective"in n.style)a=E("@media ("+r.join("transform-3d),(")+"modernizr)");return a};d.csstransitions=function(){return q("transitionProperty")};
for(var C in d)if(F(d,C)){t=C.toLowerCase();e[t]=d[C]();D.push((e[t]?"":"no-")+t)}e.crosswindowmessaging=e.postmessage;e.historymanagement=e.history;e.addTest=function(a,b){a=a.toLowerCase();if(!e[a]){b=!!b();n.className+=" "+(b?"":"no-")+a;e[a]=b;return e}};j.cssText="";A=f=null;y.attachEvent&&function(){var a=g.createElement("div");a.innerHTML="<elem></elem>";return a.childNodes.length!==1}()&&function(a,b){function c(k){for(var h=-1;++h<G;)k.createElement(u[h])}function o(k,h){for(var l=-1,i=k.length,
v,H=[];++l<i;){v=k[l];if((h=v.media||h)!="screen")H.push(o(v.imports,h),v.cssText)}return H.join("")}var u="abbr|article|aside|audio|canvas|details|figcaption|figure|footer|header|hgroup|mark|meter|nav|output|progress|section|summary|time|video".split("|"),G=u.length,M=RegExp("(^|\\s)(abbr|article|aside|audio|canvas|details|figcaption|figure|footer|header|hgroup|mark|meter|nav|output|progress|section|summary|time|video)","gi"),N=RegExp("<(/*)(abbr|article|aside|audio|canvas|details|figcaption|figure|footer|header|hgroup|mark|meter|nav|output|progress|section|summary|time|video)",
"gi"),O=RegExp("(^|[^\\n]*?\\s)(abbr|article|aside|audio|canvas|details|figcaption|figure|footer|header|hgroup|mark|meter|nav|output|progress|section|summary|time|video)([^\\n]*)({[\\n\\w\\W]*?})","gi"),I=b.createDocumentFragment(),w=b.documentElement,J=w.firstChild,s=b.createElement("body"),x=b.createElement("style"),p;c(b);c(I);J.insertBefore(x,J.firstChild);x.media="print";a.attachEvent("onbeforeprint",function(){var k=-1,h=o(b.styleSheets,"all"),l=[],i;for(p=p||b.body;(i=O.exec(h))!=null;)l.push((i[1]+
i[2]+i[3]).replace(M,"$1.iepp_$2")+i[4]);for(x.styleSheet.cssText=l.join("\n");++k<G;){h=b.getElementsByTagName(u[k]);l=h.length;for(i=-1;++i<l;)if(h[i].className.indexOf("iepp_")<0)h[i].className+=" iepp_"+u[k]}I.appendChild(p);w.appendChild(s);s.className=p.className;s.innerHTML=p.innerHTML.replace(N,"<$1font")});a.attachEvent("onafterprint",function(){s.innerHTML="";w.removeChild(s);w.appendChild(p);x.styleSheet.cssText=""})}(y,g);e._enableHTML5=true;e._version="1.6";n.className=n.className.replace(/\bno-js\b/,
"")+" js";n.className+=" "+D.join(" ");return e}(this,this.document);
